ops_manager: 
  project: 
  api_user: 
  api_password: 
  base_url: https://cloud.mongodb.com

kubernetes:
  namespace: 
  config_map_name: 
  secret_name: 

# Logger can be either: DEV or PROD
logger: DEV